title: "StudyBase"
description: "A specialized repository of techniques, strategies, and notes across various academic subjects."
theme: minima
baseurl: "/StudyBase"
url: "https://thekunalprashant.github.io"

markdown: kramdown
kramdown:
  math_engine: mathjax

plugins:
  - jekyll-feed
  - jekyll-last-modified-at

words_per_minute: 200

# Custom variables
popular_topics:
  - Value Substitution